### ISSUE TITLE
Copyright

### ISSUE THREAD

**Issue by DeMaximilianster** [JoshLmao/DarkestDungeonResponseBot#1]
Hello. I am sorry if this issue is offtop, but I need some help. So the thing is: I wanted to create a Telegram Bot that will send Ancestor's quotes, and I want to use your voice_files.json to get all the links and quotes. Should I somehow make a credit like "Inspired and created with the help of Josh Shepherd"? And if yes, how should I make it? I am not familiar with all these copyright stuff.

**Comment by JoshLmao** [comment]
The issue of copyright wouldn't be with me, it would be with the creators of Darkest Dungeon. However, I don't think they are concerned with people using the voices lines for this reason.

Also, feel free to use the voice_files.json file for your own project. I don't mind for just that file and no need to credit me like that. A simple "Thanks to JoshLmao" or something like that is okay, if you wish 😊

**Comment by DeMaximilianster** [comment]
Okay, thanks you!
